baseurl = "https://zigtag.github.io/"
languageCode = "en-us"
theme = "hello-friend-ng"
publishdir = "public"

[author]
  name = "ZigTag"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 PST"

  homeSubtitle = "by ZigTag"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by ZigTag"
  keywords = "homepage, blog, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "github"
    url = "https://github.com/ZigTag"

[languages]
  [languages.en]
    title = "Welcome ~/"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://choosealicense.com/licenses/mit/">MIT</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"