baseurl = "https://zigtag.dev/"
title = "zigtag.dev"
theme = "Coder"
publishdir = "public"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"
disable_comments = true

[params]
author = "Katlyn Courtade"
info = "Professional Software Developer"
description = "My personal website"
keywords = "blog,developer,personal"
avatarurl = "https://avatars3.githubusercontent.com/u/17077422"

colorscheme = "dark"

# favicon_32 = "/img/favicon-32x32.png"
# favicon_16 = "/img/favicon-16x16.png"

footercontent = '<p>Website licensed under the <a href="https://choosealicense.com/licenses/mit/">MIT License</a></p>'

hidecredits = false
hidecopyright = false

rtl = false

math = false
custom_css = ["css/custom.css"]

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/ZigTag"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/katlyn-courtade-080331226/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab fa-2x"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
# [[params.social]]
#     name = "Twitter"
#     icon = "fab fa-twitter fa-2x"
#     weight = 3
#     url = "https://twitter.com/johndoe/"
# 
# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "/about/"
[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"
